#!/usr/bin/env bash
# Stage portfolio media assets for upload to narendranathe/resume2.
#
# Reads from static/ and static/originals/ in the portfolio repo, writes the
# canonical resume2 layout (headshots/, og/, previews/, manifest.json) to
# build/resume2-staging/. Computes sha256 hashes (first 8 chars) for each
# file and bakes them into manifest.json.
#
# This script does NOT push to resume2. It produces a directory you can
# copy or sync into a local clone of narendranathe/resume2 and push from
# there. Idempotent: re-running rebuilds build/resume2-staging/ from
# current portfolio assets.
#
# Per scope-lock decision: favicons + site.webmanifest + apple-touch-icon
# STAY in portfolio /static/ (brand chrome, not personal identity).
# resume.pdf STAYS at portfolio /static/resume.pdf per v0.1.0-experimental
# contract.
#
# Usage:
#     bash scripts/m1-stage-resume2-assets.sh
#     rsync -av build/resume2-staging/ ../resume2/
#     cd ../resume2 && git add . && git commit -m "..." && git push

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STAGE="$REPO_ROOT/build/resume2-staging"

cd "$REPO_ROOT"

# Required source files. Missing any of these = abort.
declare -a REQUIRED_SOURCES=(
  "static/og-image.jpg"
  "static/preview-linkedin.png"
  "static/preview-substack.png"
  "static/preview-github.png"
  "static/originals/headshot-fullbody.jpg"
  "static/originals/headshot-fullbody.avif"
  "static/originals/headshot-fullbody.webp"
  "static/originals/headshot-fullbody-800.jpg"
  "static/originals/headshot-fullbody-800.avif"
  "static/originals/headshot-fullbody-800.webp"
)

# Optional sources. Missing = warn + skip, don't abort.
declare -a OPTIONAL_SOURCES=(
  "static/originals/headshot-portrait.jpg"
  "static/originals/headshot-portrait.avif"
  "static/originals/headshot-portrait.webp"
)

echo "[stage] checking source files in $REPO_ROOT"
missing=0
for src in "${REQUIRED_SOURCES[@]}"; do
  if [[ ! -f "$src" ]]; then
    echo "  MISSING (required): $src" >&2
    missing=$((missing + 1))
  fi
done
if [[ $missing -gt 0 ]]; then
  echo "[stage] $missing required source(s) missing. Run scripts/snap-favicon.py to regenerate, then retry." >&2
  exit 1
fi

echo "[stage] resetting $STAGE"
rm -rf "$STAGE"
mkdir -p "$STAGE/headshots" "$STAGE/og" "$STAGE/previews"

# ── copy files into canonical layout ─────────────────────────────────────

echo "[stage] copying headshots"
for src in "${REQUIRED_SOURCES[@]}" "${OPTIONAL_SOURCES[@]}"; do
  [[ -f "$src" ]] || continue
  case "$src" in
    static/og-image.jpg)
      cp "$src" "$STAGE/og/og-image.jpg" ;;
    static/preview-linkedin.png)
      cp "$src" "$STAGE/previews/linkedin.png" ;;
    static/preview-substack.png)
      cp "$src" "$STAGE/previews/substack.png" ;;
    static/preview-github.png)
      cp "$src" "$STAGE/previews/github.png" ;;
    static/originals/headshot-fullbody-800.*)
      ext="${src##*.}"
      cp "$src" "$STAGE/headshots/fullbody-800.$ext" ;;
    static/originals/headshot-fullbody.*)
      ext="${src##*.}"
      cp "$src" "$STAGE/headshots/fullbody.$ext" ;;
    static/originals/headshot-portrait.*)
      ext="${src##*.}"
      cp "$src" "$STAGE/headshots/portrait.$ext" ;;
  esac
done

# ── compute hashes ───────────────────────────────────────────────────────

short_sha() {
  shasum -a 256 "$1" 2>/dev/null | cut -c1-8 \
    || sha256sum "$1" | cut -c1-8
}

OG_HASH="$(short_sha "$STAGE/og/og-image.jpg")"
FULLBODY_HASH="$(short_sha "$STAGE/headshots/fullbody.jpg")"
FULLBODY_800_HASH="$(short_sha "$STAGE/headshots/fullbody-800.jpg")"

# ── write manifest.json ──────────────────────────────────────────────────

GEN_AT="$(date +%Y-%m-%d)"

# Build manifest dynamically from files that actually landed in the staging
# dir (so missing avif/webp variants don't get advertised as present).
PORTRAIT_HASH=""
[[ -f "$STAGE/headshots/portrait.jpg" ]] && PORTRAIT_HASH="$(short_sha "$STAGE/headshots/portrait.jpg")"

OG_HASH_VAL="$OG_HASH" \
FULLBODY_HASH_VAL="$FULLBODY_HASH" \
FULLBODY_800_HASH_VAL="$FULLBODY_800_HASH" \
PORTRAIT_HASH_VAL="$PORTRAIT_HASH" \
GEN_AT_VAL="$GEN_AT" \
STAGE_DIR="$STAGE" \
python3 - <<'PY'
import json, os, pathlib

stage = pathlib.Path(os.environ["STAGE_DIR"])
manifest = {
    "schema_version": "1.0.0",
    "generated_at": os.environ["GEN_AT_VAL"],
    "note": "Generated by scripts/m1-stage-resume2-assets.sh. Rerun the stager after replacing source files in portfolio static/originals/.",
    "headshots": {},
    "og": {},
    "previews": {},
}

headshot_variants = [
    ("portrait_jpg",     "/headshots/portrait.jpg"),
    ("portrait_avif",    "/headshots/portrait.avif"),
    ("portrait_webp",    "/headshots/portrait.webp"),
    ("fullbody_jpg",     "/headshots/fullbody.jpg"),
    ("fullbody_avif",    "/headshots/fullbody.avif"),
    ("fullbody_webp",    "/headshots/fullbody.webp"),
    ("fullbody_800_jpg",  "/headshots/fullbody-800.jpg"),
    ("fullbody_800_avif", "/headshots/fullbody-800.avif"),
    ("fullbody_800_webp", "/headshots/fullbody-800.webp"),
]
for key, path in headshot_variants:
    if (stage / path.lstrip("/")).exists():
        manifest["headshots"][key] = path

if os.environ.get("FULLBODY_HASH_VAL"):
    manifest["headshots"]["fullbody_version_hash"] = os.environ["FULLBODY_HASH_VAL"]
if os.environ.get("FULLBODY_800_HASH_VAL"):
    manifest["headshots"]["fullbody_800_version_hash"] = os.environ["FULLBODY_800_HASH_VAL"]
if os.environ.get("PORTRAIT_HASH_VAL"):
    manifest["headshots"]["portrait_version_hash"] = os.environ["PORTRAIT_HASH_VAL"]

manifest["og"]["image"]        = "/og/og-image.jpg"
manifest["og"]["version_hash"] = os.environ["OG_HASH_VAL"]

manifest["previews"] = {
    "linkedin": "/previews/linkedin.png",
    "substack": "/previews/substack.png",
    "github":   "/previews/github.png",
}

(stage / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
PY

# ── summary ──────────────────────────────────────────────────────────────

echo
echo "[stage] staged $(find "$STAGE" -type f | wc -l | tr -d ' ') file(s) under $STAGE"
echo
echo "  og/og-image.jpg              version_hash=$OG_HASH"
echo "  headshots/fullbody.jpg       version_hash=$FULLBODY_HASH"
echo "  headshots/fullbody-800.jpg   version_hash=$FULLBODY_800_HASH"
[[ -n "${PORTRAIT_HASH:-}" ]] && echo "  headshots/portrait.jpg       version_hash=$PORTRAIT_HASH"
echo
echo "Next:"
echo "  1. Review the staged tree:    ls -R $STAGE"
echo "  2. Sync into a resume2 clone: rsync -av $STAGE/ ../resume2/"
echo "  3. Commit + push from resume2: cd ../resume2 && git add . && git commit -m 'feat: initial media layout' && git push"
echo "  4. Run smoke checks:          bash scripts/m1-smoke-checks.sh"
echo "  5. Update CONFIG.identity in config.js: see docs/m1-resume2-setup.md Step 8."
